export enum MobileSyncOperationType {
  CREATE_INSPECTION = 'CREATE_INSPECTION',
  UPSERT_INSPECTION_ANSWER = 'UPSERT_INSPECTION_ANSWER',
  CREATE_INSPECTION_FINDING = 'CREATE_INSPECTION_FINDING',
  CLOSE_INSPECTION = 'CLOSE_INSPECTION',
  CREATE_INCIDENT = 'CREATE_INCIDENT',
  UPLOAD_ATTACHMENT = 'UPLOAD_ATTACHMENT',
}
