export enum MobileSyncStatus {
  LOCAL_DRAFT = 'LOCAL_DRAFT',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SYNCED = 'SYNCED',
  ERROR = 'ERROR',
  CONFLICT = 'CONFLICT',
  CANCELLED = 'CANCELLED',
}
