export enum Role {
  ADMIN = 'ADMIN',
  VIEWER = 'VIEWER',

  INSPECTOR = 'INSPECTOR',
  INSPECTION_RESPONSIBLE = 'INSPECTION_RESPONSIBLE',
  INSPECTION_CLOSURE_VERIFIER = 'INSPECTION_CLOSURE_VERIFIER',

  SPR_RESPONSIBLE = 'SPR_RESPONSIBLE',
  SPR_AREA_MANAGER = 'SPR_AREA_MANAGER',
  SPR_SUSTAINABILITY_SPECIALIST = 'SPR_SUSTAINABILITY_SPECIALIST',
  SPR_ENVIRONMENT_MANAGER = 'SPR_ENVIRONMENT_MANAGER',

  INCIDENT_GENERATOR = 'INCIDENT_GENERATOR',
  INCIDENT_ENV_VALIDATOR = 'INCIDENT_ENV_VALIDATOR',
  INCIDENT_ENV_COORDINATOR = 'INCIDENT_ENV_COORDINATOR',
  INCIDENT_SUPERINTENDENT = 'INCIDENT_SUPERINTENDENT',
  INCIDENT_ICAM_LEAD = 'INCIDENT_ICAM_LEAD',

  CONTROL_VERIFIER = 'CONTROL_VERIFIER',
  CONTROL_OWNER = 'CONTROL_OWNER',
  CONTROL_SUPERINTENDENT = 'CONTROL_SUPERINTENDENT',
  CONTROL_MANAGER = 'CONTROL_MANAGER',
  CONTROL_CORPORATE_APPROVER = 'CONTROL_CORPORATE_APPROVER',

  /** @deprecated Se migra a roles funcionales específicos. */
  SUPERVISOR = 'SUPERVISOR',
  /** @deprecated Se migra a roles funcionales específicos. */
  APPROVER = 'APPROVER',
}
